### ISSUE TITLE
Can't Register New Flags

### ISSUE THREAD

**Issue by Elxafil** [Nutty101/nuNPC_Destinations#2]
Upon  startup I get this error:

`[20:07:19] [Server thread/ERROR]: [Citizens] New flags cannot be registered at this time initializing NPC_Destinations v2.0.8
[20:07:19] [Server thread/WARN]: java.lang.IllegalStateException: New flags cannot be registered at this time
[20:07:19] [Server thread/WARN]: 	at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:57)
[20:07:19] [Server thread/WARN]: 	at net.livecar.nuttyworks.npc_destinations.worldguard.WorldGuard_Plugin.registerFlags(WorldGuard_Plugin.java:41)
[20:07:19] [Server thread/WARN]: 	at net.livecar.nuttyworks.npc_destinations.DestinationsPlugin.onLoad(DestinationsPlugin.java:83)
[20:07:19] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.enableSubPlugins(Citizens.java:136)
[20:07:19] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onEnable(Citizens.java:297)
[20:07:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[20:07:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:07:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:07:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[20:07:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[20:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
[20:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
[20:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
[20:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[20:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[20:07:19] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by Nutty101** [comment]
That happens if the plugin does not register before worldGuard kicks off its onEnable. Really shouldn't happen but for one reason or another my plugin didnt run first. Seems wacked. What build of worldguard do you have? Can you paste that in here?
